# Default values for backbone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# postgres user
postgresUser: legacyweb

# database password (change me)
dbPassword: 'supersecretpassword'

# redis password
redisPassword: 'supersecretpassword'

# Change this to the local path you want to mount on your master node
volumePath: /legacyweb/db

# Node you want the local db mount to be on
masterNode: 'myMaster'

# You can leave these default
dbInternalPort: 27017
dbServicePort: 5432
redisPort: 6379
webHttpPort: 8080
persistentDbPath: '/var/lib/postgresql/data/pgdata'
postgresDbName: legacyweb
dbVolumeSize: 4Gi

# This will be updated with each new app
locations:
- path: '/'
  directives:
  - 'root   /usr/share/nginx/html;'
  - 'index  index.html index.htm;'