# Default values for backbone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Port db runs on
dbInternalPort: 27017
dbServicePort: 5432

# Port redis runs on
redisPort: 6379

# postgres user
postgresUser: legacyweb

# database password (change me)
dbPassword: 'supersecretpassword'

# Change this to the local path you want to mount on your master node
volumePath: /legacyweb/db

# Node you want the local db mount to be on
masterNode: 'myMaster'

# You can leave these default
persistentDbPath: '/var/lib/postgresql/data/pgdata'
postgresDbName: legacyweb
dbVolumeSize: 4Gi