apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.dbVolumeSize }}
  local:
    path: {{ .Values.volumePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.masterNode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage