apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: legacyweb-nginx
  labels:
    app: legacyweb-nginx
spec:
  selector:
    matchLabels:
      app: legacyweb-nginx
  template:
    metadata:
      labels:
        app: legacyweb-nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: legacyweb-nginx
          image: 'nginx:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.webHttpPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-volume
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
